# Generated by Django 6.0.2 on 2026-02-20 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(default='main', max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('framework', models.CharField(max_length=50)),
                ('plan_type', models.CharField(max_length=20)),
                ('port', models.IntegerField(default=3000)),
            ],
        ),
        migrations.CreateModel(
            name='WebApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('repo_url', models.URLField()),
                ('owner', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnvVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='apps.environment')),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(blank=True, max_length=100, null=True)),
                ('public_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('cpu', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('environment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apps.environment')),
            ],
        ),
        migrations.AddField(
            model_name='environment',
            name='webapp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='apps.webapp'),
        ),
    ]
